root: ./docs

structure:
  readme: README.md
  summary: SUMMARY.md

# Only include documentation files
include:
  - docs/**

# Explicitly exclude everything else
exclude:
  - src/**
  - public/**
  - scripts/**
  - supabase/**
  - netlify-env/**
  - node_modules/**
  - dev-docs/**
  - "*.json"
  - "*.js"
  - "*.mjs"
  - "*.ts"
  - "*.log"
  - "*.toml"