[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[edge_functions]]
  function = "send-push-notification"
  path = "/.netlify/edge-functions/send-push-notification"